import slugify from "../../utils/slugify";

export default {
  title: "Groups & Parties",
  name: "groupsPage",
  type: "document",
  //__experimental_actions: ['update', /* 'create', 'delete', */ 'publish'],
  fields: [
    {
      title: "Title",
      name: "title",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "slug",
      type: "slug",
      title: "Slug",
      description:
        'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = "";
          if (doc.title) {
            titleSlug = `${doc.title}`;
          } else {
            titleSlug = "";
          }

          return `${titleSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`),
      },
      validation: (Rule) => Rule.required(),
    },
    // here is where we add the new fields
  ],
  preview: {
    select: {
      title: "title",
    },
    prepare({ title }) {
      return {
        title,
      };
    },
  },
};
