import slugify from "../../utils/slugify";

export default {
  title: "Locations",
  name: "location",
  type: "document",
  groups: [
    {
      name: "switches",
      title: "Switches",
    },
    {
      name: "info",
      title: "Information",
    },
    {
      name: "seo",
      title: "SEO",
    },
  ],
  fields: [
    {
      title: "Publish Menu?",
      name: "publishMenu",
      type: "boolean",
      description: "Defaults to false. Set to true ready to publish",
      group: "switches",
      initialValue: false,
    },
    {
      title: "Publish Careers Link?",
      name: "publishCareers",
      type: "boolean",
      description: "Defaults to false. Set to true ready to publish",
      group: "switches",
      initialValue: false,
    },
    {
      title: "Publish Hours?",
      name: "publishHours",
      type: "boolean",
      description: "Defaults to false. Set to true ready to publish",
      group: "switches",
      initialValue: false,
    },
    {
      title: "Publish Prices?",
      name: "publishPrices",
      type: "boolean",
      description: "Defaults to false. Set to true ready to publish",
      group: "switches",
      initialValue: false,
    },
    {
      title: "Title",
      description: "The name of this location",
      name: "title",
      type: "string",
      group: "info",
      validation: (Rule) => Rule.required(),
    },
    {
      title: "Long Title",
      description: "Example: Plano, TX",
      name: "longTitle",
      type: "string",
      group: "info",
    },
    {
      name: "image",
      type: "defaultImage",
      title: "Image",
      group: "info",
    },
    {
      name: "map",
      type: "geopoint",
      title: "Map",
      group: "info",
    },
    {
      name: "slug",
      type: "slug",
      title: "Slug",
      group: "seo",
      description:
        'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = "";
          if (doc.title) {
            titleSlug = `${doc.title}`;
          } else {
            titleSlug = "";
          }

          return `${titleSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`),
      },
      validation: (Rule) => Rule.required(),
    },
    {
      title: "SEO / Share Settings",
      name: "seo",
      type: "seo",
      group: "seo",
    },
  ],
  preview: {
    select: {
      title: "title",
    },
  },
};
